
meta_product_name: "Atelier 409"
meta_title: "Atelier 409 - Collectif de developpeurs et créateurs de sites"
meta_description: "Créons ensemble votre site. Atelier de conception-réalisation de sites internet. Devis 100% gratuit. Laissez-nous vous guider par notre collectif pour la réalisation de votre site internet"
meta_image: "favicon.png.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
